import { Command } from "commander";
import * as path from "path";
import * as fs from "fs";
import { Logger, AppError, handleError } from "../utils/logger.js";
import { findProjectRoot } from "../core/project.js";
import { LuaBridge, LUA_JSON_ENCODER } from "../core/lua-bridge.js";
import { getConfigPathForEnv, LUA_CONFIG_LOAD } from "../core/config.js";
import { parseSchemaFile } from "../core/schema-parser.js";

interface SchemaGenerateOptions {
  name?: string;
  output?: string;
}

/** Find Jade source directory by searching parent directories */
function findJadeSource(projectRoot: string): string | null {
  // Check common relative paths from project root
  const candidates = [
    path.join(projectRoot, "jade", "src"),
    path.join(projectRoot, "..", "jade", "src"),
    path.join(projectRoot, "..", "..", "jade", "src"),
  ];
  for (const candidate of candidates) {
    if (fs.existsSync(path.join(candidate, "jade", "init.lua"))) {
      return candidate;
    }
  }
  // Check JADE_PATH environment variable
  const envPath = process.env.JADE_PATH;
  if (envPath && fs.existsSync(path.join(envPath, "jade", "init.lua"))) {
    return envPath;
  }
  return null;
}

export function generateBarrel(modelNames: string[]): string {
  const sorted = [...modelNames].sort();
  const namesLua = sorted.map(n => `"${n}"`).join(", ");
  return `-- Auto-generated by esmeralda generate
-- Lazy model barrel: require("jade.generated")
-- Unitary: Models.User   Full: pairs(Models)

local Jade = require("jade")

local CACHE = {}
local AVAILABLE = { ${namesLua} }
local NAMES = {}
for i, n in ipairs(AVAILABLE) do NAMES[i] = n end

local proxy = {}

function proxy:modelNames()
  local copy = {}
  for i, n in ipairs(NAMES) do copy[i] = n end
  return copy
end

function proxy:reload(name)
  if name then
    CACHE[name] = nil
  else
    for k in pairs(CACHE) do CACHE[k] = nil end
  end
end

function proxy:clearCache()
  for k in pairs(CACHE) do CACHE[k] = nil end
end

return setmetatable(proxy, {
  __index = function(_, key)
    if CACHE[key] then return CACHE[key] end
    local is_model = false
    for _, n in ipairs(AVAILABLE) do
      if n == key then is_model = true break end
    end
    if not is_model then return nil end

    local ok, model = pcall(require, "jade.generated." .. key)
    if not ok then
      local path = "jade/generated/" .. key .. ".lua"
      ok, model = pcall(dofile, path)
    end
    if ok and type(model) == "table" then
      local driver = Jade.driver and select(2, pcall(Jade.driver)) or nil
      if driver and model.configure then
        pcall(function() model:configure(driver) end)
      end
      CACHE[key] = model
      return model
    end
    return nil
  end,
  __pairs = function()
    local i = 0
    return function()
      i = i + 1
      local n = NAMES[i]
      if not n then return nil end
      return n, proxy[n]
    end
  end,
})
`;
}

export function registerGenerate(program: Command): void {
  program
    .command("generate")
    .description("Generate migration from .jade schema (standard)")
    .option("-n, --name <name>", "Migration name")
    .option("--preview", "Preview SQL without generating file")
    .option("--run", "Generate and immediately run the migration")
    .option("-o, --output <dir>", "Output directory (default: schema/)")
    .option("-f, --file <path>", "Schema file path (default: auto-detect)")
    .action(async (options: SchemaGenerateOptions & { file?: string; preview?: boolean; run?: boolean }) => {
      try {
        const projectRoot = findProjectRoot();
        if (!projectRoot) {
          throw AppError.notInitialized();
        }

        Logger.info("Generating from .jade schema...");

        // Find schema file: explicit flag > .jade in schema/ > schema.lua
        let schemaDefPath: string;
        if (options.file) {
          schemaDefPath = path.resolve(projectRoot, options.file);
        } else {
          const jadeDir = path.join(projectRoot, "schema");
          const jadeFiles = fs.existsSync(jadeDir)
            ? fs.readdirSync(jadeDir).filter(f => f.endsWith(".jade"))
            : [];
          if (jadeFiles.length > 0) {
            schemaDefPath = path.join(jadeDir, jadeFiles[0]);
          } else {
            schemaDefPath = path.join(projectRoot, "schema.lua");
          }
        }

        if (!fs.existsSync(schemaDefPath)) {
          Logger.error("Schema file not found.");
          Logger.info("");
          Logger.info("Expected one of:");
          Logger.info("  - schema/models.jade  (declarative .jade file)");
          Logger.info("  - schema.lua          (Lua table format)");
          Logger.info("");
          Logger.info("Or specify explicitly:");
          Logger.info("  esmeralda schema-generate -f path/to/schema.jade");
          process.exit(1);
        }

        const isJade = schemaDefPath.endsWith(".jade");
        Logger.info(`  Using: ${path.relative(projectRoot, schemaDefPath)}`);

        const outputDir = options.output || "schema";
        const jadeSrc = findJadeSource(projectRoot);
        const luaPackagePath = [
          projectRoot.replace(/\\/g, "/") + "/?.lua",
          projectRoot.replace(/\\/g, "/") + "/?/init.lua",
          ...(jadeSrc ? [jadeSrc.replace(/\\/g, "/") + "/?.lua", jadeSrc.replace(/\\/g, "/") + "/?/init.lua"] : []),
        ].join(";");
        const bridge = new LuaBridge("lua", luaPackagePath);
        const { configPath, envConfigPath } = getConfigPathForEnv(projectRoot);

        let script: string;
        if (isJade) {
          // Parse .jade file and generate full models + migration
          script = `
${LUA_JSON_ENCODER}
local jade = require("jade")
${LUA_CONFIG_LOAD}
jade.configure(_cfg)
local f = io.open(ARGS.schemaDefPath, "r")
if not f then error("Cannot open file: " .. ARGS.schemaDefPath) end
local content = f:read("*a")
f:close()
local schema = jade.Declarative.parsedeclarativeSchema(content)

-- Generate full model files
local model_files = jade.Declarative.generateAllModels(schema)

-- Generate migration
local migration = jade.Declarative.generateMigration(schema, ARGS.migrationName or "create_tables")

-- Build result: models + migration
local result = { models = {}, migration = migration }
for filename, file_content in pairs(model_files) do
    table.insert(result.models, { filename = filename, content = file_content })
end

print(_json_encode(result))
          `;
        } else {
          // Parse schema.lua using dofile
          script = `
local jade = require("jade")
${LUA_CONFIG_LOAD}
jade.configure(_cfg)
local schema_def = dofile(ARGS.schemaDefPath)
local files = jade.Declarative.toLuaFiles(schema_def)
local parts = {}
for filename, file_content in pairs(files) do
    local esc_fn = filename:gsub('\\\\', '\\\\\\\\'):gsub('"', '\\\\"'):gsub('\\n', '\\\\n'):gsub('\\r', '\\\\r')
    local esc_fc = file_content:gsub('\\\\', '\\\\\\\\'):gsub('"', '\\\\"'):gsub('\\n', '\\\\n'):gsub('\\r', '\\\\r')
    table.insert(parts, '{"filename":"' .. esc_fn .. '","content":"' .. esc_fc .. '"}')
end
print('[' .. table.concat(parts, ',') .. ']')
          `;
        }

        const migrationName = options.name || "create_tables";
        const result: { models: Array<{ filename: string; content: string }>; migration: string } = await bridge.executeSafeJson(script, {
          configPath,
          envConfigPath,
          schemaDefPath,
          migrationName,
        });

        // Write model files to jade/generated/
        const modelsDir = path.join(projectRoot, "jade", "generated");
        fs.mkdirSync(modelsDir, { recursive: true });

        const modelNames: string[] = [];
        for (const file of result.models) {
          const filePath = path.join(modelsDir, file.filename);
          fs.writeFileSync(filePath, file.content, "utf-8");
          Logger.info(`  Generated: jade/generated/${file.filename}`);
          if (file.filename.endsWith(".lua")) {
            modelNames.push(file.filename.replace(/\.lua$/, ""));
          }
        }

        // Barrel with lazy loading — unitary or full access via proxy
        const barrel = generateBarrel(modelNames);
        const barrelPath = path.join(modelsDir, "init.lua");
        fs.writeFileSync(barrelPath, barrel, "utf-8");
        Logger.info("  Generated: jade/generated/init.lua");

        // Write migration file
        const timestamp = Date.now().toString();
        const migrationDir = path.join(projectRoot, "migrations");
        fs.mkdirSync(migrationDir, { recursive: true });
        const migrationFilename = `${timestamp}_${migrationName}.lua`;
        const migrationFile = path.join(migrationDir, migrationFilename);
        fs.writeFileSync(migrationFile, result.migration, "utf-8");
        Logger.info(`  Generated: migrations/${migrationFilename}`);

        Logger.success(`Generated ${result.models.length} model(s) + barrel + migration`);
        Logger.info("");
        Logger.info("Usage:");
        Logger.info('  local Models = require("jade.generated")  -- lazy');
        Logger.info("  local User = Models.User                 -- unitary");

        // Run migration immediately if --run flag
        if (options.run) {
          Logger.info("Running migration...");
          const runScript = `
${LUA_JSON_ENCODER}
local jade = require("jade")
${LUA_CONFIG_LOAD}
jade.configure(_cfg)
jade.migration.init(jade.driver())
local migration = dofile(ARGS.migrationPath)
migration.up()
print("OK")
          `;
          await bridge.executeSafe(runScript, {
            configPath,
            envConfigPath,
            migrationPath: migrationFile.replace(/\\/g, "/"),
          });
          Logger.success("Migration applied");
        }
      } catch (error: unknown) {
        handleError(error);
      }
    });
}

interface SchemaDiffOptions {
  preview?: boolean;
}

function findSchemaFile(projectRoot: string): { path: string; isJade: boolean } | null {
  const schemaDir = path.join(projectRoot, "schema");
  if (fs.existsSync(schemaDir)) {
    const jadeFiles = fs.readdirSync(schemaDir).filter(f => f.endsWith(".jade"));
    if (jadeFiles.length > 0) {
      return { path: path.join(schemaDir, jadeFiles[0]), isJade: true };
    }
  }
  const luaPath = path.join(projectRoot, "schema.lua");
  if (fs.existsSync(luaPath)) {
    return { path: luaPath, isJade: false };
  }
  return null;
}

function schemaDiffAction(options: SchemaDiffOptions): void {
  (async () => {
    try {
      const projectRoot = findProjectRoot();
      if (!projectRoot) {
        throw AppError.notInitialized();
      }

      Logger.info("Comparing schema with database...");

      const bridge = new LuaBridge();
      const { configPath, envConfigPath } = getConfigPathForEnv(projectRoot);
      const schemaFile = findSchemaFile(projectRoot);
      const schemaDir = path.join(projectRoot, "schema");

      if (!schemaFile) {
        Logger.error("No schema file found. Create schema/models.jade or schema.lua.");
        process.exit(1);
      }

      Logger.info(`  Using: ${path.relative(projectRoot, schemaFile.path)}`);

      // Support both schema.lua (declarative) and schema/ (entity files)
      const useSchemaDir = !schemaFile && fs.existsSync(schemaDir);

      if (useSchemaDir) {
        // Read schema from entity files in schema/ directory
        const files = fs.readdirSync(schemaDir).filter(f => f.endsWith(".lua") && f !== "init.lua");
        const entities: string[] = [];
        for (const file of files) {
          const content = fs.readFileSync(path.join(schemaDir, file), "utf-8");
          const parsed = parseSchemaFile(content);
          for (const ent of parsed) {
            entities.push(ent.tableName);
          }
        }

        if (entities.length === 0) {
          Logger.warn("No entities found in schema/");
          return;
        }

        Logger.info(`Found ${entities.length} entities in schema/`);
        Logger.info("Use 'esmeralda db sync' to compare and apply changes.");
        return;
      }

      const schemaPath = schemaFile.path;
      const isJade = schemaFile.isJade;

      let schemaLoadLua: string;
      if (isJade) {
        schemaLoadLua = `local f = io.open(ARGS.schemaPath, "r")\nif not f then error("Cannot open: " .. ARGS.schemaPath) end\nlocal content = f:read("*a")\nf:close()\nlocal parsed = jade.Declarative.parsedeclarativeSchema(content)\nlocal schema_def = { models = parsed.models }`;
      } else {
        schemaLoadLua = `local schema_def = dofile(ARGS.schemaPath)`;
      }

      const script = `
local jade = require("jade")
${LUA_CONFIG_LOAD}
jade.configure(_cfg)

local tables = jade.driver():execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name")
local current_schema = { models = {} }

for _, row in ipairs(tables) do
    local table_name = row.table_name
    local cols = jade.driver():execute("SELECT column_name, data_type, character_maximum_length, is_nullable, column_default FROM information_schema.columns WHERE table_name = '" .. table_name:gsub("'", "''") .. "' ORDER BY ordinal_position")

    local fields = {}
    for _, col in ipairs(cols) do
        local field = {
            name = col.column_name,
            type = col.data_type,
            not_null = col.is_nullable == "NO",
        }
        if col.character_maximum_length then
            field.length = col.character_maximum_length
        end
        if col.column_default and col.column_default:find("nextval") then
            field.primary_key = true
        end
        fields[col.column_name] = field
    end

    current_schema.models[table_name] = {
        tableName = table_name,
        fields = fields,
    }
end

${schemaLoadLua}
local diff = jade.Declarative.diff(current_schema, schema_def)
-- Write result as simple key-value output (no dkjson dependency)
local function encodeSimple(v)
    if type(v) == "string" then return '"' .. v:gsub('\\\\', '\\\\\\\\'):gsub('"', '\\\\"'):gsub('\\n', '\\\\n') .. '"'
    elseif type(v) == "number" then return tostring(v)
    elseif type(v) == "boolean" then return tostring(v)
    elseif type(v) == "nil" then return "null"
    elseif type(v) == "table" then
        -- Check if array
        if #v > 0 or next(v) == nil then
            local parts = {}
            for _, item in ipairs(v) do parts[#parts+1] = encodeSimple(item) end
            return '[' .. table.concat(parts, ',') .. ']'
        else
            local parts = {}
            for k, val in pairs(v) do parts[#parts+1] = '"' .. tostring(k) .. '":' .. encodeSimple(val) end
            return '{' .. table.concat(parts, ',') .. '}'
        end
    end
    return "null"
end
print(encodeSimple(diff))
      `;

      const diff = await bridge.executeSafeJson(script, {
        configPath,
        envConfigPath,
        schemaPath,
      });

      if (diff.tables_to_create.length > 0) {
        Logger.info("Tables to create:");
        for (const table of diff.tables_to_create) {
          Logger.info(`  + ${table.tableName}`);
        }
      }

      if (diff.tables_to_drop.length > 0) {
        Logger.info("Tables to drop:");
        for (const table of diff.tables_to_drop) {
          Logger.info(`  - ${table.tableName}`);
        }
      }

      if (diff.tables_to_alter.length > 0) {
        Logger.info("Tables to alter:");
        for (const table of diff.tables_to_alter) {
          Logger.info(`  ~ ${table.model.tableName}`);
          if (table.changes.columns_to_add.length > 0) {
            for (const col of table.changes.columns_to_add) {
              Logger.info(`    + ${col.name}`);
            }
          }
          if (table.changes.columns_to_drop.length > 0) {
            for (const col of table.changes.columns_to_drop) {
              Logger.info(`    - ${col.name}`);
            }
          }
        }
      }

      if (diff.tables_to_create.length === 0 && diff.tables_to_drop.length === 0 && diff.tables_to_alter.length === 0) {
        Logger.info("No changes detected.");
        return;
      }

      if (options.preview) {
        Logger.info("Preview mode - no migration generated.");
        return;
      }

      Logger.info("Generating migration...");
      Logger.success("Migration generation not yet implemented.");
    } catch (error: unknown) {
      handleError(error);
    }
  })();
}

export function registerSchemaDiff(db: Command): void {
  db.command("diff")
    .description("Compare current schema with database and generate migration")
    .option("--preview", "Preview changes without generating migration")
    .action(schemaDiffAction);

  db.command("schema-diff")
    .description("Compare current schema with database and generate migration (alias for 'db diff')")
    .option("--preview", "Preview changes without generating migration")
    .action(schemaDiffAction)
    .addHelpText("after", "\nTip: Use 'db diff' instead.");
}
