import { Command } from "commander";
import * as path from "path";
import * as fs from "fs";
import { Logger } from "../utils/logger.js";
import { findProjectRoot, getConfigPath } from "../core/project.js";
import { parseSchemaFile, EntityDef } from "../core/schema-parser.js";
import { DiffEngine } from "../core/diff-engine.js";
import { generateMigration } from "../core/migration-generator.js";
import { writeFile, ensureDir } from "../core/file-manager.js";

interface GenerateOptions {
  name?: string;
  preview?: boolean;
}

export function registerGenerate(program: Command): void {
  program
    .command("generate")
    .description("Generate migration from schema diff")
    .option("-n, --name <name>", "Migration name")
    .option("--preview", "Preview SQL without generating file")
    .action(async (options: GenerateOptions) => {
      const projectRoot = findProjectRoot();
      if (!projectRoot) {
        Logger.error("Not a Jade project. Run 'esmeralda init' first.");
        process.exit(1);
      }

      const schemaDir = path.join(projectRoot, "schema");
      if (!fs.existsSync(schemaDir)) {
        Logger.error("Schema directory not found.");
        process.exit(1);
      }

      Logger.info("Reading schema files...");

      // Parse all schema files
      const entities: EntityDef[] = [];
      const files = fs.readdirSync(schemaDir).filter(f => f.endsWith(".lua") && f !== "init.lua");

      for (const file of files) {
        const content = fs.readFileSync(path.join(schemaDir, file), "utf-8");
        const parsed = parseSchemaFile(content);
        entities.push(...parsed);
      }

      if (entities.length === 0) {
        Logger.warn("No entities found in schema/");
        return;
      }

      Logger.info(`Found ${entities.length} entities`);

      // Generate migration
      const timestamp = Date.now();
      const name = options.name || "migration";
      const filename = `${timestamp}_${name}.lua`;

      const migrationDir = path.join(projectRoot, "migrations");
      ensureDir(migrationDir);

      const upCode = generateMigration(entities, "up");
      const downCode = generateMigration(entities, "down");

      const content = `-- Migration: ${name}
-- Generated by Esmeralda
-- ${new Date().toISOString()}

local Jade = require("jade")

local M = {}

function M.up()
${upCode}
end

function M.down()
${downCode}
end

return M
`;

      if (options.preview) {
        Logger.info("Migration preview:");
        console.log(content);
        return;
      }

      const filePath = path.join(migrationDir, filename);
      writeFile(filePath, content);

      Logger.success(`Migration created: ${filename}`);
    });
}
