import { Command } from "commander";
import * as path from "path";
import * as fs from "fs";
import { Logger, AppError } from "../utils/logger.js";
import { findProjectRoot } from "../core/project.js";
import { parseSchemaFile, EntityDef } from "../core/schema-parser.js";
import { generateMigration } from "../core/migration-generator.js";
import { writeFile, ensureDir } from "../core/file-manager.js";
import { loadState, saveState, inferMigrationName } from "../core/schema-state.js";

/** Generate a 14-digit timestamp compatible with Jade's os.date("%Y%m%d%H%M%S") */
function jadeTimestamp(): string {
  const now = new Date();
  const pad = (n: number) => n.toString().padStart(2, "0");
  return `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
}

interface GenerateOptions {
  name?: string;
  preview?: boolean;
  database?: string;
}

export function registerGenerateLegacy(program: Command): void {
  program
    .command("generate:legacy")
    .description("[DEPRECATED] Generate migration from schema/*.lua files. Use 'generate' with .jade instead.")
    .option("-n, --name <name>", "Migration name")
    .option("--preview", "Preview SQL without generating file")
    .option("-d, --database <name>", "Database to generate for")
    .action(async (options: GenerateOptions) => {
      Logger.warn("This command is deprecated. Use 'esmeralda generate' with a .jade schema file instead.");
      Logger.warn("  See: https://jade-docs.vercel.app/docs/declarative-schema");
      Logger.info("");

      const projectRoot = findProjectRoot();
      if (!projectRoot) {
        throw AppError.notInitialized();
      }

      const schemaDir = path.join(projectRoot, "schema");
      if (!fs.existsSync(schemaDir)) {
        throw AppError.schemaDirNotFound();
      }

      Logger.info("Reading legacy schema files (*.lua)...");

      // Parse all schema files
      const entities: EntityDef[] = [];
      const files = fs.readdirSync(schemaDir).filter(f => f.endsWith(".lua") && f !== "init.lua");

      for (const file of files) {
        const content = fs.readFileSync(path.join(schemaDir, file), "utf-8");
        const parsed = parseSchemaFile(content);
        entities.push(...parsed);
      }

      if (entities.length === 0) {
        Logger.warn("No entities found in schema/");
        return;
      }

      Logger.info(`Found ${entities.length} entities`);

      // Load previous state and infer migration name
      const state = loadState(projectRoot);
      const name = options.name || inferMigrationName(entities, state);

      if (!options.name && state) {
        const prev = new Set(state.entities.map(e => e.tableName));
        const curr = new Set(entities.map(e => e.tableName));
        const added = [...curr].filter(t => !prev.has(t));
        const removed = [...prev].filter(t => !curr.has(t));
        if (added.length === 0 && removed.length === 0) {
          Logger.warn("No schema changes detected since last generate.");
        }
      }

      // Generate migration
      const timestamp = jadeTimestamp();
      const migrationDir = path.join(projectRoot, "migrations");
      const filename = `${timestamp}_${name}.lua`;

      // Read esmeralda version from package.json
      let esmeraldaVersion = "unknown";
      try {
        const pkgPath = path.join(__dirname, "..", "..", "package.json");
        const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
        esmeraldaVersion = pkg.version || "unknown";
      } catch {}

      ensureDir(migrationDir);

      const upCode = generateMigration(entities, "up");
      const downCode = generateMigration(entities, "down");

      const content = `-- Migration: ${name}
-- Generated by Esmeralda v${esmeraldaVersion}
-- ${new Date().toISOString()}

local jade = require("jade")

local M = {}

function M.up()
${upCode}
end

function M.down()
${downCode}
end

return M
`;

      if (options.preview) {
        Logger.info("Migration preview:");
        console.log(content);
        return;
      }

      const filePath = path.join(migrationDir, filename);
      writeFile(filePath, content);

      // Save current schema state
      saveState(projectRoot, entities);

      Logger.success(`Migration created: ${filename}`);
    });
}
