import { Command } from "commander";
import * as fs from "fs";
import * as path from "path";
import { Logger, AppError, handleError } from "../utils/logger.js";
import { findProjectRoot } from "../core/project.js";
import { detectDriver, getDialect, type SQLDialect, type DriverKind } from "../core/sql-dialect.js";
import { LuaBridge, LUA_JSON_ENCODER } from "../core/lua-bridge.js";
import { getDatabaseNames, parseMultiDbConfig } from "../core/multi-db.js";

interface PullOptions {
  database?: string;
  table?: string;
  interactive?: boolean;
}

/**
 * Experimental: introspect a live database and emit a declarative .jade schema.
 *
 * Naming (ALINHAMENTO §7.7):
 *   - default / primary DB  → schema/models.jade
 *   - named secondary DB    → schema/{db_name}_models.jade
 */
export function registerPull(program: Command): void {
  program
    .command("pull")
    .description("[Experimental] Introspect database → declarative .jade schema")
    .option("-d, --database <name>", "Database name (multi-db config key, or label for output file)")
    .option("-t, --table <name>", "Only pull a single table")
    .option("-i, --interactive", "Prompt for database when multi-db is configured")
    .action(async (options: PullOptions) => {
      try {
        Logger.warn("esmeralda pull is EXPERIMENTAL — output may need manual cleanup.");
        const projectRoot = findProjectRoot();
        if (!projectRoot) {
          throw AppError.notInitialized();
        }

        const multiDbNames = getDatabaseNames(projectRoot);
        let dbLabel = options.database;

        if (!dbLabel && multiDbNames.length > 1) {
          if (options.interactive || process.stdin.isTTY) {
            Logger.info("Available databases:");
            multiDbNames.forEach((n, i) => Logger.info(`  [${i + 1}] ${n}`));
            // Non-TTY / non-interactive: default to first
            dbLabel = multiDbNames[0];
            Logger.info(`Using first database: ${dbLabel}`);
          } else {
            dbLabel = multiDbNames[0];
          }
        }
        if (!dbLabel) {
          dbLabel = "default";
        }

        const isDefault = !options.database || options.database === "default" ||
          (parseMultiDbConfig(projectRoot)?.default === dbLabel);
        const outName = isDefault ? "models.jade" : `${dbLabel}_models.jade`;
        const outPath = path.join(projectRoot, "schema", outName);

        const driverKind = detectDriver(projectRoot);
        const dialect = getDialect(driverKind);
        Logger.info(`Introspecting ${driverKind}${dbLabel !== "default" ? ` (${dbLabel})` : ""}...`);

        const configPath = path.join(projectRoot, "jade.config.lua").replace(/\\/g, "\\\\");
        const bridge = new LuaBridge();

        const listScript = `
          ${LUA_JSON_ENCODER}
          local jade = require("jade")
          local config = dofile("${configPath}")
          jade.configure(config)
          local tables = jade.driver():execute([[${dialect.tableListQuery()}]])
          local result = {}
          for _, row in ipairs(tables) do
            ${driverKind === "sqlite"
              ? "table.insert(result, row.table_name or row.name)"
              : "table.insert(result, row.table_name)"}
          end
          print(_json_encode(result))
        `;

        const tables: string[] = await bridge.executeSafeJson(listScript);
        const filtered = options.table ? tables.filter(t => t === options.table) : tables;
        if (filtered.length === 0) {
          Logger.warn("No tables found to pull.");
          process.exit(0);
        }

        Logger.info(`Found ${filtered.length} table(s)`);

        const models: string[] = [];
        for (const tableName of filtered) {
          const meta = await introspectTable(bridge, configPath, dialect, driverKind, tableName);
          const modelName = toPascalCase(tableName);
          models.push(renderJadeModel(modelName, tableName, meta));
          Logger.info(`  + ${modelName}`);
        }

        const header = `-- Generated by esmeralda pull (experimental)
-- Source: ${dbLabel === "default" ? "primary database" : `database "${dbLabel}"`}
-- Review before generate / migrate.

`;
        fs.mkdirSync(path.dirname(outPath), { recursive: true });
        fs.writeFileSync(outPath, header + models.join("\n\n") + "\n", "utf-8");

        Logger.success(`Wrote ${path.relative(projectRoot, outPath)}`);
        Logger.info("Next: review, then `esmeralda generate` (use -f if not models.jade)");
      } catch (error: unknown) {
        handleError(error);
      }
    });
}

/* ─── Introspection (lean copy for experimental pull) ────────── */

interface NormalizedColumn {
  column_name: string;
  data_type: string;
  character_maximum_length: number | null;
  is_nullable: string;
  column_default: string | null;
}

interface NormalizedForeignKey {
  column_name: string;
  foreign_table_name: string;
  foreign_column_name: string;
}

interface TableMetadata {
  columns: NormalizedColumn[];
  foreignKeys: NormalizedForeignKey[];
}

async function introspectTable(
  bridge: LuaBridge,
  configPath: string,
  dialect: SQLDialect,
  driverKind: DriverKind,
  tableName: string
): Promise<TableMetadata> {
  const columnScript = `
    ${LUA_JSON_ENCODER}
    local jade = require("jade")
    local config = dofile("${configPath}")
    jade.configure(config)
    local rows = jade.driver():execute([[${dialect.columnListQuery(tableName)}]])
    print(_json_encode(rows))
  `;
  const rawCols: any[] = await bridge.executeSafeJson(columnScript);
  const columns = normalizeColumns(rawCols, driverKind);

  let foreignKeys: NormalizedForeignKey[] = [];
  try {
    const fkQuery = dialect.foreignKeyQuery(tableName);
    if (fkQuery) {
      const fkScript = `
        ${LUA_JSON_ENCODER}
        local jade = require("jade")
        local config = dofile("${configPath}")
        jade.configure(config)
        local rows = jade.driver():execute([[${fkQuery}]])
        print(_json_encode(rows))
      `;
      foreignKeys = normalizeForeignKeys(await bridge.executeSafeJson(fkScript), driverKind);
    }
  } catch {
    /* optional */
  }

  return { columns, foreignKeys };
}

function normalizeColumns(raw: any[], driverKind: DriverKind): NormalizedColumn[] {
  if (driverKind === "sqlite") {
    return raw.map((c: any) => ({
      column_name: c.name,
      data_type: normalizeSqliteType(c.type),
      character_maximum_length: extractLength(c.type),
      is_nullable: c.notnull === 1 ? "NO" : "YES",
      column_default: c.dflt_value,
    }));
  }
  return raw;
}

function normalizeSqliteType(typeStr: string): string {
  if (!typeStr) return "text";
  const upper = typeStr.toUpperCase();
  if (upper.includes("INT")) return "integer";
  if (upper.includes("CHAR") || upper.includes("CLOB") || upper.includes("TEXT")) return "text";
  if (upper.includes("REAL") || upper.includes("FLOA") || upper.includes("DOUB")) return "real";
  return "text";
}

function extractLength(typeStr: string): number | null {
  if (!typeStr) return null;
  const match = typeStr.match(/\((\d+)\)/);
  return match ? parseInt(match[1], 10) : null;
}

function normalizeForeignKeys(raw: any[], driverKind: DriverKind): NormalizedForeignKey[] {
  if (driverKind === "sqlite") {
    return raw.map((fk: any) => ({
      column_name: fk.from,
      foreign_table_name: fk.table,
      foreign_column_name: fk.to,
    }));
  }
  return raw;
}

function toPascalCase(str: string): string {
  return str
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

function mapJadeType(col: NormalizedColumn): string {
  const t = (col.data_type || "").toLowerCase();
  if (t.includes("serial") || t === "integer" || t === "int") {
    return col.character_maximum_length ? "Integer()" : "Integer()";
  }
  if (t.includes("bigint")) return "BigInt()";
  if (t.includes("bool")) return "Boolean()";
  if (t.includes("timestamp")) return "Timestamp()";
  if (t.includes("date")) return "Date()";
  if (t.includes("uuid")) return "UUID()";
  if (t.includes("json")) return "JSON()";
  if (t.includes("text") || t.includes("clob")) return "Text()";
  if (t.includes("numeric") || t.includes("decimal")) return "Decimal()";
  if (t.includes("real") || t.includes("float") || t.includes("double")) return "Float()";
  const len = col.character_maximum_length;
  return len ? `String(${len})` : "String()";
}

function renderJadeModel(modelName: string, tableName: string, meta: TableMetadata): string {
  const lines: string[] = [];
  lines.push(`model ${modelName} {`);
  lines.push(`    table = "${tableName}"`);

  const fkByColumn = new Map(meta.foreignKeys.map(fk => [fk.column_name, fk]));

  for (const col of meta.columns) {
    if (col.column_name === "id") continue; // convention: auto PK
    let field = `    ${col.column_name} = ${mapJadeType(col)}`;
    if (col.is_nullable === "NO") field += "!";
    if (col.column_default != null && !String(col.column_default).includes("nextval")) {
      const d = col.column_default;
      if (d === "true" || d === "false") field += `.default(${d})`;
      else if (/^-?\d+(\.\d+)?$/.test(d)) field += `.default(${d})`;
    }
    lines.push(field);

    const fk = fkByColumn.get(col.column_name);
    if (fk) {
      const target = toPascalCase(singularize(fk.foreign_table_name));
      lines.push(`    ${singularize(fk.foreign_table_name)} = belongsTo(${target})`);
    }
  }

  lines.push(`}`);
  return lines.join("\n");
}

function singularize(str: string): string {
  if (str.endsWith("ies")) return str.slice(0, -3) + "y";
  if (str.endsWith("ses") || str.endsWith("xes") || str.endsWith("zes"))
    return str.slice(0, -2);
  if (str.endsWith("us") || str.endsWith("ss")) return str;
  if (str.endsWith("s")) return str.slice(0, -1);
  return str;
}
